version: "3.9"
services:
    service1:
        build: ./Apartments
        ports:
            - "5001:5000"
    service2:
        build: ./Booking
        ports:
            - "5002:5000"
    service3:
        build: ./Search
        ports:
            - "5003:5000"
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
           - 5672:5672
           - 15672:15672
