version: "3.9"
services:
    apartment:
        build: ./Apartment
        ports:
            - "5001:5000"
        depends_on:
            rabbitmq:
                condition: service_healthy
    booking:
        build: ./Booking
        ports:
            - "5002:5000"
        depends_on:
            - "apartment"
    search:
        build: ./Search
        ports:
            - "5003:5000"
        depends_on:
            - "booking"
#    gateway:
#        build: ./Gateway
#        ports:
#            - "5004:5000"
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
           - 5672:5672
           - 15672:15672
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 5s
            timeout: 5s
            retries: 3
